### PR TITLE
Migrate Mod to use Jotunn 2.0.11

### PR DESCRIPTION
**Pull request by baruchvlz**
[ValheimLib](https://github.com/Valheim-Modding/ValheimLib) was deprecated some time ago and merged onto [Jotunn](https://github.com/Valheim-Modding/Jotunn). This PR migrates the mod to use the new Jotunn mod API.

Big thanks to Jules from the JotunnMod disc for helping me figure out an issue with the ItemConfig JSON.

*NOTE* There might be some left over files from the rebase that might need to be removed, if so I can take care of it.

### CODE REVIEW

**Comment by OhhLoz** [comment]
Hey, Thanks alot for this. I was running into errors whilst trying to do this myself but I hadn't really put alot of time into it. I'm not very familiar with pull requests however I wanted to keep the master branch clear of any project files / IDE files and only files that are essential to the mod. I'm not sure how to merge only parts of the commit in order to achieve that however.

Again, much appreciated. BTW: what was wrong with the ItemConfig JSON?

**Comment by baruchvlz** [comment]
> I wanted to keep the master branch clear of any project files / IDE files

I don't think there are any IDE files. Some of the files are boilerplate from [JotunnModStub](https://github.com/Valheim-Modding/JotunnModStub/) , but I'll take another look which can be removed. If you have a list of files you see in the PR that you don't want I can also remove those.

> BTW: what was wrong with the ItemConfig JSON?

There was nothing wrong per-se, what happen was that the `repairStation` property had an empty string and Jotunn couldn't parse it. But they have the [fix already in the main branch](https://github.com/Valheim-Modding/Jotunn/commit/171cce0e9aab143b830df792b7fee2dafefaad27) and will be release with 2.0.12.

**Comment by OhhLoz** [comment]
Hey thanks for the reply, I didn't mean to come across as ungrateful or anything.

I just want to have as little files here as necessary, things like the unity project settings, visual studio solution(might be standard practice?), visual studio project settings, configs.

Basically I haven't included a Unity project or the Visual Studio stuff since I've already set them up and felt it wasn't necessary to the core mod, only the files from those.

Again, I don't mean to be ungrateful and I do appreciate it.
I probably shouldn't have included repairStation at all since I never used it.

**Comment by baruchvlz** [comment]
No hard feelings mate :)

I'll leave the VS Solution in case anyone else who wants to work on the project uses VS. I removed the boilerplate Unity files and left the `Icons` and `Assets` folder with the HoneyPlus things. (Could you verify these work? I don't know how to use Unity that well, want to be sure the assets are not messed up)

**Pull request merged**
